version: "3.8"

services:
  api:
    image: bybatkhuu/fastapi-template:4.0.1-231017
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FASTAPI_TEMPLATE_APP_PORT: ${FASTAPI_TEMPLATE_APP_PORT:-8000}
    volumes:
      - "./volumes/storage/fastapi-template/logs:/var/log/fastapi-template"
      - "./volumes/storage/fastapi-template/data:/var/lib/fastapi-template"
    ports:
      - "${FASTAPI_TEMPLATE_APP_PORT:-8000}:${FASTAPI_TEMPLATE_APP_PORT:-8000}"
    tty: true
